config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :study_years
    resources :departments
    resources :memberships
    root to: 'users#index'
  end

  root to: 'visitors#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :members do
    resources :subscriptions, except: [:index, :show]
  end
end

app/models/member.rb
class Member < ActiveRecord::Base

  belongs_to :study_year
  belongs_to :department
  has_many :subscriptions
  has_many :memberships, through: :subscriptions, class_name: 'Membership'
  has_many :excluded_memberships, through: :memberships, class_name: 'Membership'

  accepts_nested_attributes_for :department
  accepts_nested_attributes_for :study_year

  validates_presence_of :name, :first_name
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, presence: true
  validates_uniqueness_of :student_card, if: :has_student_card?
  validates_uniqueness_of :phone
  validates_inclusion_of :gender, in: %w{M W}

  def has_student_card?
    not (student_card.nil? or student_card.empty?)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  # noinspection RailsParamDefResolve
  before_action :authenticate_user!

  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.fetch(:member, []).permit(:name, :first_name, :email, :department_id, :study_year_id, :gender, :phone, :student_card, :birthday=>[])
    end
end

app/helpers/members_helper.rb
module MembersHelper
  # @param [Department] department
  def display_department(department)
    department.nil? ? t('not_filled') : department.name
  end
  # @param [StudyYear] sy
  def display_study_year(sy)
    sy.nil? ? t('other') : sy.name
  end
end

app/views/members/_form.html.haml
= simple_form_for(@member) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-6= f.input :name
      .col-md-6= f.input :first_name
    .row
      .col-md-6= f.input :email
      .col-md-6= f.input :phone
    .row
      .col-md-6= f.input :birthday
      .col-md-6= f.input :student_card
    .row
      .col-md-6= f.association :study_year
      .col-md-6= f.association :department

  .form-actions
    = f.button :submit, value: 'OK', class: %w(btn-primary btn-block)

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1=t('ava.members.list_of_members')

%table.table.table-striped
  %thead
    %tr
      %th=t('activerecord.attributes.member.student_card')
      %th=t('activerecord.attributes.member.name')
      %th=t('activerecord.attributes.member.first_name')
      %th=t('activerecord.attributes.member.email')
      %th
      %th
      %th

  %tbody
    - @members.each do |member|
      %tr
        %td= member.student_card
        %td= member.name
        %td= member.first_name
        %td= member.email
        %td= link_to t('show'), member
        %td= link_to t('edit'), edit_member_path(member)
        %td= link_to t('destroy'), member, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%h2="#{@member.name.upcase} #{@member.first_name}"

.form-horizontal
  .form-group
    %label.control-label.col-sm-2=t('activerecord.attributes.member.email')
    .col-sm-10
      %p.form-control-static= @member.email
  .form-group
    %label.control-label.col-sm-2=t('activerecord.attributes.member.phone')
    .col-sm-10
      %p.form-control-static= @member.phone
  .row
    .col-sm-6
      .form-group
        %label.control-label.col-sm-4=t('activerecord.attributes.member.department')
        .col-sm-8
          %p.form-control-static= display_department @member.department
    .col-sm-6
      .form-group
        %label.control-label.col-sm-4=t('activerecord.attributes.member.study_year')
        .col-sm-8
          %p.form-control-static= display_study_year @member.study_year

  .row
    .col-md-6
      .form-group
        %label.control-label.col-sm-4=t('activerecord.attributes.member.memberships')
        .col-sm-8
          .form-control-static
            %ul
              - @member.subscriptions.each do |s|
                %li
                  = s.membership.name
                  .pull-right
                    = link_to member_subscription_path(member_id: @member.id, id: s.id), method: :delete, confirm: t('ava.subscriptions.delete_confirmation'), class: %w{btn btn-danger btn-sm} do
                      %i.glyphicon.glyphicon-trash
              - if @member.subscriptions.empty?
                %li.text-muted=t('ava.members.no_memberships')
            = link_to new_member_subscription_path(member_id:@member.id), class: %w{btn btn-success btn-block btn-sm} do
              %i.glyphicon.glyphicon-plus-sign
              %span= t('add')

.row
  .col-sm-4.col-sm-offset-1= link_to 'Back', members_path, class: %w{btn btn-default btn-block}
  .col-sm-4.col-sm-offset-2= link_to 'Edit', edit_member_path(@member), class: %w{btn btn-primary btn-block}